version: 2.1

working_directory: &working_directory
  working_directory: ~/project

jobs:
  install_dependencies:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/project
          paths:
            - .cache

  run_cypress_tests:
    <<: *working_directory
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/project
      - run:
          name: Running cypress tests
          command: npm test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  build_and_test:
    jobs:
      - install_dependencies
      - run_cypress_tests:
          requires:
            - install_dependencies
